export enum NodeType {
  INITIAL = "INITIAL",
  MANUAL_TRIGGER = "MANUAL_TRIGGER",
  HTTP_REQUEST = "HTTP_REQUEST",
  GOOGLE_FORM_TRIGGER = "GOOGLE_FORM_TRIGGER",
  STRIPE_TRIGGER = "STRIPE_TRIGGER",
  DEEPSEEK = "DEEPSEEK",
  QWEN = "QWEN",
  LLAMA = "LLAMA",
  DISCORD = "DISCORD",
  SLACK = "SLACK",
  
} 
export enum CredentialsType {
   DEEPSEEK = "DEEPSEEK",
  QWEN = "QWEN", 
  OPENAI = "OPENAI", 
  LLAMA = "LLAMA",
}